### ISSUE TITLE
Refactor storage config - remove "documentdb" from appsettings.ini

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-dotnet#24]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

Storage should be easily swapped out for another storage type in the future. We should use only [messages] and [alarms], and [keyvaluestorage] to track storage type used by each.

# Expected behavior

...
Messages and Alarms will call their own independent storage connection string from the StorageClient.

**Comment by ppathan** [comment]
@jillcary Re-open if not done.
