### ISSUE TITLE
[Bug] Improve QueryBuilder Query Format

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-dotnet#25]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

The current implementation has 2 problems:
- it gets slower and slower when increasing the "skip". It should use only TOP, on a reverse-ordered list
- it hits the pagination limit, e.g. when skip is > max number of records returned by docDB

# Expected behavior

increasing skip should not slow down the query
the pagination limit shouldn't be hit when skip > max records

# Possible solution

Update the following line of code in QueryBuilder.cs:
queryBuilder.Append("SELECT TOP " + (skip + limit) + " * FROM c WHERE (c[`doc.schema`] = `" + schemaName + "`");

# Context and Environment
* Operating System: all
* .NET Runtime

**Comment by ppathan** [comment]
@jillcary Re-open if not done.
