### ISSUE TITLE
[Bug] Investigate Gaps in Telemetry Chart

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-dotnet#30]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

The telemetry chart is returning odd gaps in the data, investigate the messages endpoint to make sure all of the data is being returned from documentDb.

# Steps to reproduce

look at the "floor 2"  device group in the current demo, notice gaps in the data.

**Comment by ppathan** [comment]
@jillcary Re-open is still an issue.
