### ISSUE TITLE
"Rule Deleted" - Alarms for deleted rules cannot access rule details for maintenance page

### ISSUE THREAD

**Issue by jillcary** [Azure/device-telemetry-dotnet#33]
# Type of issue

- [x] Bug
- [ ] New feature
- [x] Improvement

# Description

The maintenance displays all open alarms. These alarms are all associated with a rule, and the only information that the alarm has about the rule is the ID (long number that isn't user friendly), and the rule description. To display the rule name and associated info like conditions, the UI needs to query for the RuleID.

Since maintenance page displays all alarms, the alarms that are associated with a deleted rule show as well, but the UI can no longer get the information for that rule since it's been deleted, meaning the UI will need to show "Rule Deleted"

**If we wish to KEEP the Alarms for deleted rules:**
- add rule name & other details to alarm (right now alarms only have the rule ID and description which is never displayed to the user)

**If we wish to DELETE all alarms for deleted rules:**
- delete rule should also delete or close corresponding alarms.

**Comment by ppathan** [comment]
@jillcary Should this be tracked as new feature? Can you open item in TFS is that is the case.
